language: node_js
sudo: enabled
node_js:
  - 7
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE repo;'
  - mysql '-u root repo < db/repo.txt;'
install:
  - npm install
script:
- echo "skipping tests"
