language: node_js
sudo: enabled
node_js:
  - 7
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE repo; repo < db/repo.txt; CREATE DATABASE repo_queue; repo_queue < db/repo_queue.txt;'
install:
  - npm install
script:
- echo "skipping tests"
- node repo.js
